# Tool: https://docs.github.com/en/code-security/dependabot
# Checks for vulnerabilities in the Pub package manager
version: 2
updates:
  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/cicd_poc/" # Change this to the Pub package manager directory
    schedule:
      interval: "weekly"
