name: 'Dependency Check'
on:
   push:
     branches:
       - master
   pull_request:
     types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  dependency-check:
    runs-on: ubuntu-latest
        defaults:
      run:
        working-directory: /cicd_poc
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Install Dart SDK'
        uses: dart-lang/setup-dart@v1.3
      - name: Check licenses installszzzzz
        run: | 
          dart pub global activate license_checker_for_github_action 
      - name: Check licenses
        run: | 
          dart_license_checker --show-transitive-dependencies --fail-on-copyleft
