name: 'Dependency Check'
on:
   push:
     branches:
       - master
   pull_request:
     types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check licenses install 
        run: | 
          dart pub global activate license_checker_for_github_action 
      - name: Check licenses
        run: | 
          dart_license_checker --show-transitive-dependencies --fail-on-copyleft
