# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: 'Dependency Review'
on:
   push:
     branches:
       - master
   pull_request:
     types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cicd_poc/
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
        with:
           fail-on-severity: low
           deny-licenses: AGPL-3.0, EPL-2.0, GPL-2.0, GPL-3.0, LGPL-2.1, MPL-2.0
s