name: 'Dependency Review'
on:
   push:
     branches:
       - master
   pull_request:
     types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  checkout-repo:
    - name: Checkout Repository
        uses: actions/checkout@v3
  dart-license-check:
    needs: checkout-repo
    runs-on: ubuntu-latest
    env:
      PROJECT_DIRECTORY: ./cicd_poc
    steps:
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
      - name: Install project dependencies
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: flutter pub get
      - name: Install Dart license checker
        run: | 
          dart pub global activate license_checker_for_github_action
      - name: Run Dart license checker
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: | 
          dart_license_checker --show-transitive-dependencies --fail-on-copyleft
    github-dependency-review:
      needs: checkout-repo
      runs-on: ubuntu-latest
      - name: Run GitHub dependency review (vulnerabilities & licenses)
        uses: actions/dependency-review-action@v2
        with:
           fail-on-severity: low
           deny-licenses: AGPL-3.0, EPL-2.0, GPL-2.0, GPL-3.0, LGPL-2.1, MPL-2.0

